name: Check Commit Message

on: [push]

jobs:
  check-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        
      - name: Validate commit message
        run: |
          if [[ "$(git log -1 --pretty=%B)" =~ ^(feat|fix|docs|chore): ]]; then
            echo "✅ Commit message is valid."
          else
            echo "❌ Commit message must start with 'feat:', 'fix:', 'docs:', or 'chore:'"
            exit 1
          fi

          
