name: Say Hello

on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to GitHub Actions
        run: echo "🎉 Hello from GitHub Actions!"
